/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_COFFEE_PJPG_FILES           69
#define MMAP_COFFEE_PJPG_CHECKSUM        0xB1E3

enum MMAP_COFFEE_PJPG_LISTS {
    MMAP_COFFEE_PJPG_BG_PNG = 0,        /*!< BG.png */
    MMAP_COFFEE_PJPG_BREWING_PNG = 1,        /*!< Brewing.png */
    MMAP_COFFEE_PJPG_COFFEE_ILLUSTRATION_PNG = 2,        /*!< Coffee_illustration.png */
    MMAP_COFFEE_PJPG_PLAY_BUTTON_PNG = 3,        /*!< Play_button.png */
    MMAP_COFFEE_PJPG_POLYGON_PNG = 4,        /*!< Polygon.png */
    MMAP_COFFEE_PJPG_TOP_PNG = 5,        /*!< Top.png */
    MMAP_COFFEE_PJPG_ALERT_PNG = 6,        /*!< alert.png */
    MMAP_COFFEE_PJPG_ARROW_PNG = 7,        /*!< arrow.png */
    MMAP_COFFEE_PJPG_ARROWS_PNG = 8,        /*!< arrows.png */
    MMAP_COFFEE_PJPG_BEANICONS_PNG = 9,        /*!< beanicons.png */
    MMAP_COFFEE_PJPG_BEANS_WHITE_PNG = 10,        /*!< beans_white.png */
    MMAP_COFFEE_PJPG_BIG_ESPRESSO_PNG = 11,        /*!< big_espresso.png */
    MMAP_COFFEE_PJPG_BIG_LATTE_PNG = 12,        /*!< big_latte.png */
    MMAP_COFFEE_PJPG_BIG_RISTRETTO_PNG = 13,        /*!< big_ristretto.png */
    MMAP_COFFEE_PJPG_BIGBEAN_PNG = 14,        /*!< bigbean.png */
    MMAP_COFFEE_PJPG_BLE_PNG = 15,        /*!< ble.png */
    MMAP_COFFEE_PJPG_CHEVRON_PNG = 16,        /*!< chevron.png */
    MMAP_COFFEE_PJPG_CHEVRON_1_PNG = 17,        /*!< chevron_1.png */
    MMAP_COFFEE_PJPG_CLEAN_PNG = 18,        /*!< clean.png */
    MMAP_COFFEE_PJPG_CLOUDY_PNG = 19,        /*!< cloudy.png */
    MMAP_COFFEE_PJPG_CLOUDY_S_PNG = 20,        /*!< cloudy_s.png */
    MMAP_COFFEE_PJPG_CUP_PNG = 21,        /*!< cup.png */
    MMAP_COFFEE_PJPG_CUP1_PNG = 22,        /*!< cup1.png */
    MMAP_COFFEE_PJPG_CUPS_PNG = 23,        /*!< cups.png */
    MMAP_COFFEE_PJPG_DISABLEDBEAN_PNG = 24,        /*!< disabledbean.png */
    MMAP_COFFEE_PJPG_DONE_PNG = 25,        /*!< done.png */
    MMAP_COFFEE_PJPG_DONE_60_PNG = 26,        /*!< done_60.png */
    MMAP_COFFEE_PJPG_DRIZZLE_PNG = 27,        /*!< drizzle.png */
    MMAP_COFFEE_PJPG_DRIZZLE_S_PNG = 28,        /*!< drizzle_s.png */
    MMAP_COFFEE_PJPG_ESPRESSO_PNG = 29,        /*!< espresso.png */
    MMAP_COFFEE_PJPG_FOAM_PNG = 30,        /*!< foam.png */
    MMAP_COFFEE_PJPG_FOAM_BODY_PNG = 31,        /*!< foam_body.png */
    MMAP_COFFEE_PJPG_FOG_PNG = 32,        /*!< fog.png */
    MMAP_COFFEE_PJPG_FOG_S_PNG = 33,        /*!< fog_s.png */
    MMAP_COFFEE_PJPG_HUMIDITY_PNG = 34,        /*!< humidity.png */
    MMAP_COFFEE_PJPG_LANGUAGES_PNG = 35,        /*!< languages.png */
    MMAP_COFFEE_PJPG_LATTE_ILLUSTRATION_PNG = 36,        /*!< latte_illustration.png */
    MMAP_COFFEE_PJPG_LIGHT_PNG = 37,        /*!< light.png */
    MMAP_COFFEE_PJPG_PARAMETERS_PNG = 38,        /*!< parameters.png */
    MMAP_COFFEE_PJPG_PARAMETERS_1_PNG = 39,        /*!< parameters_1.png */
    MMAP_COFFEE_PJPG_PARTLY_PNG = 40,        /*!< partly.png */
    MMAP_COFFEE_PJPG_PARTLY_S_PNG = 41,        /*!< partly_s.png */
    MMAP_COFFEE_PJPG_PROFILE_PNG = 42,        /*!< profile.png */
    MMAP_COFFEE_PJPG_QUANTITY_PNG = 43,        /*!< quantity.png */
    MMAP_COFFEE_PJPG_RAIN_PNG = 44,        /*!< rain.png */
    MMAP_COFFEE_PJPG_RAIN_S_PNG = 45,        /*!< rain_s.png */
    MMAP_COFFEE_PJPG_ROLLER_PNG = 46,        /*!< roller.png */
    MMAP_COFFEE_PJPG_SETTINGS_PNG = 47,        /*!< settings.png */
    MMAP_COFFEE_PJPG_SHAPE1_PNG = 48,        /*!< shape1.png */
    MMAP_COFFEE_PJPG_SLIDER_BG_PNG = 49,        /*!< slider_bg.png */
    MMAP_COFFEE_PJPG_SNOW_PNG = 50,        /*!< snow.png */
    MMAP_COFFEE_PJPG_SNOW_S_PNG = 51,        /*!< snow_s.png */
    MMAP_COFFEE_PJPG_STANDBY_PNG = 52,        /*!< standby.png */
    MMAP_COFFEE_PJPG_SUNNY_PNG = 53,        /*!< sunny.png */
    MMAP_COFFEE_PJPG_SUNNY_S_PNG = 54,        /*!< sunny_s.png */
    MMAP_COFFEE_PJPG_TANK_PNG = 55,        /*!< tank.png */
    MMAP_COFFEE_PJPG_TASTE1_PNG = 56,        /*!< taste1.png */
    MMAP_COFFEE_PJPG_TEMP_BODY_PNG = 57,        /*!< temp_body.png */
    MMAP_COFFEE_PJPG_TEMPERATURE_PNG = 58,        /*!< temperature.png */
    MMAP_COFFEE_PJPG_THERMOMETER_PNG = 59,        /*!< thermometer.png */
    MMAP_COFFEE_PJPG_THUNDER_PNG = 60,        /*!< thunder.png */
    MMAP_COFFEE_PJPG_THUNDER_S_PNG = 61,        /*!< thunder_s.png */
    MMAP_COFFEE_PJPG_UNITS_PNG = 62,        /*!< units.png */
    MMAP_COFFEE_PJPG_WATER_PNG = 63,        /*!< water.png */
    MMAP_COFFEE_PJPG_WAVE1_PNG = 64,        /*!< wave1.png */
    MMAP_COFFEE_PJPG_WAVE_BOTTOM_PNG = 65,        /*!< wave_bottom.png */
    MMAP_COFFEE_PJPG_WAVEV1_PNG = 66,        /*!< wavev1.png */
    MMAP_COFFEE_PJPG_WAVEV2_PNG = 67,        /*!< wavev2.png */
    MMAP_COFFEE_PJPG_WIFI_PNG = 68,        /*!< wifi.png */
};
